# Generated by Django 4.2.24 on 2026-02-02 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_invoice_office_address_invoice_office_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='client_company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='client_tel',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
