# Generated by Django 4.2.24 on 2026-02-02 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_invoice_client_company_name_invoice_client_tel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='client_company_name',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='client_tel',
        ),
    ]
