# Generated by Django 4.2.24 on 2026-02-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0008_remove_invoice_client_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
