# Generated by Django 4.2.24 on 2026-03-02 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0009_alter_invoice_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
